# -*- coding: utf-8 -*-
"""Thesiswork.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uq_V9X0nt3LDsLyaErcL-4X5710D-PY5
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import precision_recall_fscore_support
from yellowbrick.classifier import ClassificationReport
from matplotlib.colors import ListedColormap
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.gaussian_process import GaussianProcessClassifier

dataset = pd.read_csv("Prediction2.csv")


x=dataset.iloc[:, 0:5].values
y=dataset.iloc[:, 8].values

dataset.head()

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
l_n = LabelEncoder()

x[:, 1]=l_n.fit_transform(x[:, 1])
x[:, 2]=l_n.fit_transform(x[:, 2])
x[:, 3]=l_n.fit_transform(x[:, 3])
x[:, 4]=l_n.fit_transform(x[:, 4])
# Decimal to binary encoder
onehotencoder=OneHotEncoder(categorical_features=[1])
x=onehotencoder.fit_transform(x).toarray()

onehotencoder=OneHotEncoder(categorical_features=[2])
x=onehotencoder.fit_transform(x).toarray()

onehotencoder=OneHotEncoder(categorical_features=[3])
x=onehotencoder.fit_transform(x).toarray()

onehotencoder=OneHotEncoder(categorical_features=[4])
x=onehotencoder.fit_transform(x).toarray()

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=10)


# # Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_x= StandardScaler()
x_train= sc_x.fit_transform(x_train)
x_test= sc_x.transform(x_test)

names = ["Logistic Regression", "Linear SVM", "Random Forest", "Adaboost", "Naive Bayes",
         "Neural Net", "KNN Classifier", "Decision Tree"]
classifiers = [
    LogisticRegression(solver='sag'),
    SVC(kernel="linear", C=0.025),
    RandomForestClassifier(max_depth=5, n_estimators=100),
    AdaBoostClassifier(n_estimators = 100),
    GaussianNB(),
    MLPClassifier(alpha=1),
    KNeighborsClassifier(39),
    DecisionTreeClassifier(max_depth=5),
    ]

for name, clf in zip(names, classifiers):
    print("=================",name,"====================")
    clf.fit(x_train, y_train)
    y_pred = clf.predict(x_test)
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))
    print(name,' accuracy is',accuracy_score(y_pred,y_test))
    precision_recall_fscore_support(y_test, y_pred, average='macro')
    print(precision_recall_fscore_support)

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
l_n = LabelEncoder()

x[:, 1]=l_n.fit_transform(x[:, 1])
x[:, 2]=l_n.fit_transform(x[:, 2])
x[:, 3]=l_n.fit_transform(x[:, 3])
x[:, 4]=l_n.fit_transform(x[:, 4])
# Decimal to binary encoder
onehotencoder=OneHotEncoder(categorical_features=[1])
x=onehotencoder.fit_transform(x).toarray()

onehotencoder=OneHotEncoder(categorical_features=[2])
x=onehotencoder.fit_transform(x).toarray()

onehotencoder=OneHotEncoder(categorical_features=[3])
x=onehotencoder.fit_transform(x).toarray()

onehotencoder=OneHotEncoder(categorical_features=[4])
x=onehotencoder.fit_transform(x).toarray()


x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=10)
# Fit to the train set
from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier(39)
classifier.fit(x_train, y_train)
y_pred= classifier.predict(x_test)
print('KNN',' accuracy is',accuracy_score(y_pred,y_test))


# Visualizing the train set result
from matplotlib.colors import ListedColormap
x_set= x_test[:, 0]
y_set= y_pred
plt.plot(x_set, y_set, label = "line 1") 

plt.title("Criminal's Age Range Prediction against Victim Count")
plt.xlabel('')
plt.ylabel("")
plt.legend()
plt.show()

x_set= x_test[:, 1]
y_set= y_pred
plt.plot(x_set, y_set, label = "line 1") 

plt.title("Criminal's Age Range Prediction against the Crime")
plt.xlabel('')
plt.ylabel("")
plt.legend()
plt.show()

x_set= x_test[:, 2]
y_set= y_pred
plt.plot(x_set, y_set, label = "line 1") 

plt.title("Criminal's Age Range Prediction against the Victim Race")
plt.xlabel('')
plt.ylabel("")
plt.legend()
plt.show()

x_set= x_test[:, 3]
y_set= y_pred
plt.plot(x_set, y_set, label = "line 1") 

plt.title("Criminal's Age Range Prediction against the Victim Sex")
plt.xlabel('')
plt.ylabel("")
plt.legend()
plt.show()

x_set= x_test[:, 4]
y_set= y_pred
plt.plot(x_set, y_set, label = "line 1") 

plt.title("Criminal's Age Range Prediction against the Area")
plt.xlabel('')
plt.ylabel("")
plt.legend()
plt.show()

